In [47]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [48]:
df = pd.read_csv(r"D:\LearningConcepts\intelipaat\ML models assignments\Decision Tree Quiz\Pokemon.csv")
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [49]:
df[df['Generation'] == 5].shape[0]

165

In [50]:
df['Defense'].max()

230

In [51]:
df[df['Defense'] == 230].shape[0]

3

In [52]:
df.isna().sum()

#               0
Name            0
Type 1          0
Type 2        386
Total           0
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [53]:
df['Type 2'].value_counts()

Type 2
Flying      97
Ground      35
Poison      34
Psychic     33
Fighting    26
Grass       25
Fairy       23
Steel       22
Dark        20
Dragon      18
Ice         14
Rock        14
Water       14
Ghost       14
Fire        12
Electric     6
Normal       4
Bug          3
Name: count, dtype: int64

In [54]:
df.corr(numeric_only= True)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,1.000000,0.119813,0.097614,0.102298,0.094786,0.088759,0.085817,0.010733,0.982516,0.153396
Total,0.119813,1.000000,0.618748,0.736211,0.612787,0.747250,0.717609,0.575943,0.048384,0.501758
HP,0.097614,0.618748,1.000000,0.422386,0.239622,0.362380,0.378718,0.175952,0.058683,0.273620
Attack,0.102298,0.736211,0.422386,1.000000,0.438687,0.396362,0.263990,0.381240,0.051451,0.345408
Defense,0.094786,0.612787,0.239622,0.438687,1.000000,0.223549,0.510747,0.015227,0.042419,0.246377
Sp. Atk,0.088759,0.747250,0.362380,0.396362,0.223549,1.000000,0.506121,0.473018,0.036437,0.448907
Sp. Def,0.085817,0.717609,0.378718,0.263990,0.510747,0.506121,1.000000,0.259133,0.028486,0.363937
Speed,0.010733,0.575943,0.175952,0.381240,0.015227,0.473018,0.259133,1.000000,-0.023121,0.326715
Generation,0.982516,0.048384,0.058683,0.051451,0.042419,0.036437,0.028486,-0.023121,1.000000,0.079794
Legendary,0.153396,0.501758,0.273620,0.345408,0.246377,0.448907,0.363937,0.326715,0.079794,1.000000

In [55]:
df['Type 2'] = df['Type 2'].fillna('None')

In [56]:
df = pd.get_dummies(df, columns=['Name', 'Type 1', 'Type 2'], drop_first=True)

In [57]:
df

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,...,Type 2_Grass,Type 2_Ground,Type 2_Ice,Type 2_None,Type 2_Normal,Type 2_Poison,Type 2_Psychic,Type 2_Rock,Type 2_Steel,Type 2_Water
0,1,318,45,49,49,65,65,45,1,False,...,False,False,False,False,False,True,False,False,False,False
1,2,405,60,62,63,80,80,60,1,False,...,False,False,False,False,False,True,False,False,False,False
2,3,525,80,82,83,100,100,80,1,False,...,False,False,False,False,False,True,False,False,False,False
3,3,625,80,100,123,122,120,80,1,False,...,False,False,False,False,False,True,False,False,False,False
4,4,309,39,52,43,60,50,65,1,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,600,50,100,150,100,150,50,6,True,...,False,False,False,False,False,False,False,False,False,False
796,719,700,50,160,110,160,110,110,6,True,...,False,False,False,False,False,False,False,False,False,False
797,720,600,80,110,60,150,130,70,6,True,...,False,False,False,False,False,False,False,False,False,False
798,720,680,80,160,60,170,130,80,6,True,...,False,False,False,False,False,False,False,False,False,False
799,721,600,80,110,120,130,90,70,6,True,...,False,False,False,False,False,False,False,False,False,True

In [58]:
X = df.drop('Legendary', axis=1)
y = df['Legendary']

In [59]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=1
)

# Decision Tree Model
model = DecisionTreeClassifier(random_state=1)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Results
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[212   7]
 [  6  15]]
              precision    recall  f1-score   support

       False       0.97      0.97      0.97       219
        True       0.68      0.71      0.70        21

    accuracy                           0.95       240
   macro avg       0.83      0.84      0.83       240
weighted avg       0.95      0.95      0.95       240

In [61]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Read data
df = pd.read_csv(r"D:\LearningConcepts\intelipaat\ML models assignments\Decision Tree Quiz\Pokemon.csv")

# Fill missing values
df["Type 2"] = df["Type 2"].fillna(df["Type 2"].mode()[0])

# Label Encode categorical columns
le = LabelEncoder()

for col in ["Name", "Type 1", "Type 2"]:
    df[col] = le.fit_transform(df[col])

# Target
y = df["Legendary"]

# Features
X = df.drop("Legendary", axis=1)

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=1
)

# Model
dt = DecisionTreeClassifier(random_state=1)
dt.fit(X_train, y_train)

# Prediction
y_pred = dt.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[214   5]
 [  4  17]]
              precision    recall  f1-score   support

       False       0.98      0.98      0.98       219
        True       0.77      0.81      0.79        21

    accuracy                           0.96       240
   macro avg       0.88      0.89      0.89       240
weighted avg       0.96      0.96      0.96       240

In [ ]:
df.

<bound method DataFrame.value_counts of        #  Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0      1    80       9      13    318  45      49       49       65       65
1      2   329       9      13    405  60      62       63       80       80
2      3   745       9      13    525  80      82       83      100      100
3      3   746       9      13    625  80     100      123      122      120
4      4   102       6       7    309  39      52       43       60       50
..   ...   ...     ...     ...    ...  ..     ...      ...      ...      ...
795  719   160      15       4    600  50     100      150      100      150
796  719   161      15       4    700  50     160      110      160      110
797  720   314      14       8    600  80     110       60      150      130
798  720   315      14       1    680  80     160       60      170      130
799  721   756       6      17    600  80     110      120      130       90

     Speed  Generation  Legendary
0       45           1      False
1       60           1      False
2       80           1      False
3       80           1      False
4       65           1      False
..     ...         ...        ...
795     50           6       True
796    110           6       True
797     70           6       True
798     80           6       True
799     70           6       True

[800 rows x 13 columns]>

In [65]:
print(df['Legendary'].value_counts())

Legendary
False    735
True      65
Name: count, dtype: int64

In [66]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from scipy.stats import entropy

data = pd.read_csv(r"D:\LearningConcepts\intelipaat\ML models assignments\Decision Tree Quiz\diabetes.csv")

# ---------------- Q15 ----------------
bp = data["BloodPressure"].copy()

bp_cat = pd.cut(
    bp,
    bins=[-np.inf,79,120,np.inf],
    labels=["Low","Normal","High"]
)

p = bp_cat.value_counts(normalize=True)
print("Q15 Entropy =", entropy(p, base=2))

# ---------------- Q17 ----------------
def calc_entropy(col):
    p = data[col].value_counts(normalize=True)
    return entropy(p, base=2)

print("\nQ17")
for c in data.columns[:-1]:
    print(c, calc_entropy(c))

# ---------------- Q18 ----------------
X = data.drop("Outcome", axis=1)
y = data["Outcome"]

tree = DecisionTreeClassifier(
    criterion="entropy",
    random_state=0,
    max_depth=1
)

tree.fit(X,y)

print("\nQ18 Root Feature =", X.columns[tree.tree_.feature[0]])

# ---------------- Q19 ----------------
print("\nQ19 Gini")
for c in data.columns[:-1]:
    p = data[c].value_counts(normalize=True)
    gini = 1 - np.sum(p**2)
    print(c, gini)

# ---------------- Q21 ----------------
df = data[data.Glucose != 0]
df = df[df.Glucose <= 75]

X = df[["Glucose"]]
y = df["Outcome"]

tree = DecisionTreeClassifier(random_state=0)
tree.fit(X,y)

print("\nQ21 Leaf =", tree.tree_.feature[0] == -2)

# ---------------- Q22 ----------------
X = data[["Pregnancies","BloodPressure"]]
y = data["Outcome"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=24
)

dt = DecisionTreeClassifier(random_state=8)
dt.fit(X_train,y_train)

pred = dt.predict(X_test)

cm = confusion_matrix(y_test,pred)

TN,FP,FN,TP = cm.ravel()

precision = TP/(TP+FP)

print("\nQ22")
print(cm)
print("Precision =", precision)

# ---------------- Q23 ----------------
X = data[["Insulin","BMI"]]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=24
)

dt = DecisionTreeClassifier(random_state=30)
dt.fit(X_train,y_train)

pred = dt.predict(X_test)

cm = confusion_matrix(y_test,pred)

TN,FP,FN,TP = cm.ravel()

recall = TP/(TP+FN)

print("\nQ23")
print(cm)
print("Recall =", recall)

Q15 Entropy = 0.8488937951699136

Q17
Pregnancies 3.4820480960305136
Glucose 6.751021001710518
BloodPressure 4.792469587589404
SkinThickness 4.5855913814785465
Insulin 4.681589542876211
BMI 7.5937573506351255
DiabetesPedigreeFunction 8.82850483152379
Age 5.028842203274248

Q18 Root Feature = Glucose

Q19 Gini
Pregnancies 0.8943922254774306
Glucose 0.9891560872395834
BloodPressure 0.956081814236111
SkinThickness 0.897884792751736
Insulin 0.7605082194010416
BMI 0.9936353895399306
DiabetesPedigreeFunction 0.9974365234375
Age 0.9589267306857638

Q21 Leaf = True

Q22
[[74 24]
 [39 17]]
Precision = 0.4146341463414634

Q23
[[77 21]
 [28 28]]
Recall = 0.5